### PR TITLE
Add more example configuration

### PR DESCRIPTION
**Pull request by AnthonyEnr1quez**
Added some more configuration to the example config with values that I am using and work.

@PierreMesure I also have a setup of using this as a kubernetes job. I can clean it up and make it more generic for an example in this repo. Not sure where you would want me to put that in the repo structure. Let me know!

Job: https://github.com/AnthonyEnr1quez/k3s-gitops/tree/main/download/flemmarr

### CODE REVIEW

**Comment by PierreMesure** [comment]
Hi @AnthonyEnr1quez! Great job! And very neat!

I'm not sure about Kubernetes because I don't use it so I always struggle to understand what part of the config does what. Maybe the easiest would be to add the link you provided to the README?

I think the config example for qBitTorrent, naming and media management will be extremely useful. I wonder if we should keep the config for EZTV, TorrentGalaxy and 1337x though. In the example, I made sure to use Internet Archive as I didn't want to mention any tracker that lists illegal material to avoid trouble 😛.

If that's OK with you, I'll remove them and add the link to reference your Kubernetes file. I'll also add your name at the bottom of the README as a contributor.

**Comment by AnthonyEnr1quez** [comment]
@PierreMesure Removed those extra indexers, I understand why :)

Ill let you edit the README, not sure where you would like to add it.

You could use this link for the kubernetes reference: https://github.com/AnthonyEnr1quez/k3s-gitops/tree/84945829dc4c116475811fca5f8476f9546b83e4/download/flemmarr

**Comment by AnthonyEnr1quez** [comment]
@PierreMesure Added some more config examples for quality definitions that I added to my config. Also updated the links to my repo, since I did some restructuring

**Comment by PierreMesure** [comment]
Amazing! I'm merging the PR! Sorry it took so long, I've drifted away from this project. If you'd like to take it over, don't hesitate to say! @RynoM was also interested but I think he hasn't had time since I gave him rights on the repo.

**Comment by AnthonyEnr1quez** [comment]
@PierreMesure I wouldn't mind becoming a maintainer, this is a useful project and I think could benefit with a few more features and testing!

**Pull request merged**
